name: com
description: An emergency alert app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #flutter packages/plugins
  splashscreen: ^1.2.0
  firebase_auth: ^0.14.0+5
  toast: ^0.1.5
  contacts_service: ^0.3.10
  permission_handler: 4.4.0+hotfix.2
  firebase_database: ^3.1.3
  firebase_core: any
  google_maps_flutter: ^0.5.11+1
  geolocator: ^5.1.1
  sms_maintained: ^0.2.5
  geocoder: ^0.2.1
  location: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #assets folder for images
  assets:
    - assets/
  fonts:
    - family: Sogoe
      fonts:
        - asset: fonts/myfont.ttf

